# Generated by Django 3.1.7 on 2021-03-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210317_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
