# Generated by Django 3.1.7 on 2021-03-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='posts',
        ),
    ]
